---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: nayaksv/master:latest
        ports:
        - containerPort: 5001
        env:
        - name: FLASK_ENV
          value: development
        - name: FLASK_DEBUG
          value: "1"
        - name: FLASK_APP
          value: app/master.py
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt/efs
      volumes:
      - name: shared-storage
        hostPath:
          path: /mnt/efs
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - port: 5001
    targetPort: 5001

